/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica;

/**
 *
 * @author Jonathan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblM = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblZ = new javax.swing.JLabel();
        m = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        z = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        rst = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblM.setText("m =");

        lblN.setText("n =");

        lblX.setText("x =");

        lblY.setText("y =");

        lblZ.setText("z =");

        m.setText("m");

        n.setText("n");

        x.setText("x");

        y.setText("y");

        z.setText("z ");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "elija la opcion", "variacion con repeticion", "variacion sin repeticion", "combinanciones", "permutaciones sin repeticion", "permutaciones con repeticion" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        rst.setText("rst");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblN)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblM)
                                    .addComponent(lblX)
                                    .addComponent(lblY)
                                    .addComponent(lblZ))
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(m)
                                    .addComponent(x)
                                    .addComponent(y)
                                    .addComponent(z)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rst, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblM)
                    .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblN)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblY)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZ)
                    .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(rst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        
        if(comboBox.getSelectedIndex() == 0) {
					
					n.setVisible(false);
					m.setVisible(false);
					lblM.setVisible(false);
					lblN.setVisible(false);
					lblX.setVisible(false);
					lblY.setVisible(false);
					lblZ.setVisible(false);
					x.setVisible(false);
					y.setVisible(false);
					z.setVisible(false);
					
					rst.setVisible(false);
					btnCalcular.setVisible(false);
					
					
					n.setText("");
					m.setText("");
					x.setText("");
					y.setText("");
					z.setText("");
				}
				
				if(comboBox.getSelectedIndex() == 1) {
					n.setVisible(true);
					m.setVisible(true);
					lblM.setVisible(true);
					lblN.setVisible(true);
					lblX.setVisible(false);
					lblY.setVisible(false);
					lblZ.setVisible(false);
					x.setVisible(false);
					y.setVisible(false);
					z.setVisible(false);
					
					rst.setVisible(true);
					btnCalcular.setVisible(true);
					
					n.setText("");
					m.setText("");
					x.setText("");
					y.setText("");
					z.setText("");
				}
				
				if(comboBox.getSelectedIndex() == 2) {
					n.setVisible(true);
					m.setVisible(true);
					lblM.setVisible(true);
					lblN.setVisible(true);
					lblX.setVisible(false);
					lblY.setVisible(false);
					lblZ.setVisible(false);
					x.setVisible(false);
					y.setVisible(false);
					z.setVisible(false);
					
					rst.setVisible(true);
					btnCalcular.setVisible(true);
					
					n.setText("");
					m.setText("");
					x.setText("");
					y.setText("");
					z.setText("");
				}
				
				if(comboBox.getSelectedIndex() == 3) {
					n.setVisible(true);
					m.setVisible(true);
					lblM.setVisible(true);
					lblN.setVisible(true);
					lblX.setVisible(false);
					lblY.setVisible(false);
					lblZ.setVisible(false);
					x.setVisible(false);
					y.setVisible(false);
					z.setVisible(false);
					
					rst.setVisible(true);
					btnCalcular.setVisible(true);
					
					n.setText("");
					m.setText("");
					x.setText("");
					y.setText("");
					z.setText("");
				}
				
				if(comboBox.getSelectedIndex() == 4) {
					n.setVisible(true);
					m.setVisible(false);
					lblM.setVisible(false);
					lblN.setVisible(true);
					lblX.setVisible(false);
					lblY.setVisible(false);
					lblZ.setVisible(false);
					x.setVisible(false);
					y.setVisible(false);
					z.setVisible(false);
					
					rst.setVisible(true);
					btnCalcular.setVisible(true);
					
					n.setText("");
					m.setText("");
					x.setText("");
					y.setText("");
					z.setText("");
				}
				
				if(comboBox.getSelectedIndex() == 5) {
					n.setVisible(true);
					m.setVisible(false);
					lblM.setVisible(false);
					lblN.setVisible(true);
					lblX.setVisible(true);
					lblY.setVisible(true);
					lblZ.setVisible(true);
					x.setVisible(true);
					y.setVisible(true);
					z.setVisible(true);
					
					rst.setVisible(true);
					btnCalcular.setVisible(true);
					
					n.setText("");
					m.setText("");
					x.setText("");
					y.setText("");
					z.setText("");
				}
    }//GEN-LAST:event_comboBoxActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if(comboBox.getSelectedIndex() == 1) {
					Repeticion v = new Repeticion(Integer.parseInt(n.getText()),Integer.parseInt(m.getText()));
					rst.setText(String.valueOf(v.variacionSinRepeticion()));
					
				}
				
				if(comboBox.getSelectedIndex() == 2) {
					Repeticion vr = new Repeticion(Integer.parseInt(n.getText()),Integer.parseInt(m.getText()));
					rst.setText(String.valueOf(vr.variacionConRepeticion()));
				}
				
				if(comboBox.getSelectedIndex() == 3) {
					Repeticion c = new Repeticion(Integer.parseInt(n.getText()),Integer.parseInt(m.getText()));
					rst.setText(String.valueOf(c.combinaciones()));
				}
				
				if(comboBox.getSelectedIndex() == 4) {
					Repeticion c = new Repeticion(Integer.parseInt(n.getText()));
					rst.setText(String.valueOf(c.permutacionesSinRepeticion()));
				}
								
				if(comboBox.getSelectedIndex() == 5) {
					Repeticion pr = new Repeticion( Integer.parseInt(n.getText()), Integer.parseInt(x.getText()), Integer.parseInt(y.getText()), Integer.parseInt(z.getText()) );
					rst.setText(String.valueOf(pr.permutacionesConRepeticion()));
				}
				
				
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel lblZ;
    private javax.swing.JTextField m;
    private javax.swing.JTextField n;
    private javax.swing.JTextField rst;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    private javax.swing.JTextField z;
    // End of variables declaration//GEN-END:variables
}
